spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: God4me@2025 # <-- Put your actual password here
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Creates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect